name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:

  deploy:
    runs-on: ubuntu-latest
    environment: production
    env:
      EXPO_PUBLIC_API_URL: ${{ secrets.EXPO_PUBLIC_API_URL }}

    steps:
    - uses: actions/checkout@v4

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Env
      shell: bash
      run: echo -e "
        EXPO_PUBLIC_API_URL=${EXPO_PUBLIC_API_URL}" > .env.production

    - name: 'Build and push image'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . -t api5frontend
        docker tag api5frontend ${{ secrets.REGISTRY_LOGIN_SERVER }}/api5frontend
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/api5frontend